title: C.E.
subtitle: A computer scientist developing practical solutions to everyday challenges.
description: >- # this means to ignore newlines until "baseurl:"
  A modified devlopr-Jekyll themed static site for hosting my developments.

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: About Me
      url: /about
    - text: Blog
      url: /blog
    - text: Contact Me
      url : /contact
    - text: Gallery
      url: /gallery

# Edit these details

author_logo: profile.png
author: C.E.
author_bio: Hi, my name is C.E. and this site is used for hosting my projects.
author_email: "cescandon@horizon.csueastbay.edu"
author_location: California
author_website_url: "https://github.com/concandon"
typewrite-text: If you build it, they will clone.

author_work_experiences:
            - company_name: USNR
              company_logo: usnr.png
              company_url: https://www.navyreserve.navy.mil/
              designation: Sailor
              description: Worked on various missions
              visibility: true
            - company_name: Kaiser Permanente
              company_logo: kp.png
              company_url: https://kp.org
              designation: IT Volunteer
              description: Worked on various IT support tasks
              visibility: true

author_education_details:
              - college_logo: csueb.png
                college_name: CSUEB
                college_url: https://csueastbay.edu/cs/
                college_degree: Comp Sci.
                description: Bachelor of Science
                visibility: true

author_project_details:
              - project_thumbnail: filler1.png
                project_title: Nutrition_App
                project_description: A project for helping with nutrition tracking.
                project_url: https://github.com/concandon/Nutrition_App
                visibility: true
              - project_thumbnail: filler2.png
                project_title: Tic-Tac-Toe
                project_description: An approach to simple design of tic-tac-toe game in c++
                project_url: https://github.com/concandon/tictactoe-ex1
                visibility: true

# social links
github_username:  concandon

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: random
hyvor_talk_website_id: #1929

# wakatime username (coding activity)
wakatime_username: concandon

# random mailchimp embedded form url (newsletter):
mailchimp_form_url: https://tsyefn.us2.list-manage.com/subscribe/post?u=8c30fac086955bae55cdd1d2b&amp;id=a143aa90ad

# formspree (contact form)
formspree_email: moqpajrk

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
# collections:
# - products

# Gallery
defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
